### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by bitkeks**
Analogue to website repo

### CODE REVIEW

**Comment by garloff** [comment]
I would have expected CC-BY-SA-4.0 as license for the newsletters.
* We have primarily text, where CC is a good match.
* -BY: We want attribution
* -SA: A weak copyleft, forcing folks that do reuse content and change it to release it again openly (so we have a chance to know, appreciate, criticize, ... it).

**Comment by fkr** [comment]
yes, this should be CC-BY-SA and not MIT for the Content - the rest of the newsletter engine (since it is jekyll) probably should be MIT (since that is the original license)

**Comment by fkr** [comment]
> yes, this should be CC-BY-SA and not MIT for the Content - the rest of the newsletter engine (since it is jekyll) probably should be MIT (since that is the original license)

I've updated this PR to have a LICENSE file in _digest/ where the contents of the newsletter lies. this way it is clear that the content of the newsletter is CC-BY-SA.

**Review by garloff — APPROVED** [review]
Thanks, looks good to me now!

**Pull request merged**
